name: Build and test dotnet environment

on: 
  pull_request: 
    branches: develop

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8.x on ubuntu
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Display .NET version
        run: dotnet --version
      
      - name: Build project
        working-directory: src
        run: dotnet build
      
      - name: Test project
        working-directory: src
        run: dotnet test
  run-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8.x on windows
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Display .NET version
        run: dotnet --version
      
      - name: Build project
        working-directory: src
        run: dotnet build
      
      - name: Test project
        working-directory: src
        run: dotnet test
  run-on-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8.x on macos
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Display .NET version
        run: dotnet --version
      
      - name: Build project
        working-directory: src
        run: dotnet build
      
      - name: Test project
        working-directory: src
        run: dotnet test